# Generated by Django 6.0.7 on 2026-07-12 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EngineRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=120, verbose_name='Project Title')),
                ('brief_description', models.TextField(verbose_name='System Overview')),
                ('core_tech_stack', models.CharField(max_length=250, verbose_name='Technologies Used')),
                ('performance_score', models.IntegerField(default=85, verbose_name='AI Optimization Score')),
                ('repository_source', models.URLField(blank=True, null=True, verbose_name='GitHub Link')),
                ('deployment_live', models.URLField(blank=True, null=True, verbose_name='Live Production URL')),
                ('display_as_flagship', models.BooleanField(default=False, verbose_name='Feature on Main Hero Grid')),
                ('registered_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Engine Registries',
            },
        ),
        migrations.CreateModel(
            name='InboundConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_identity', models.CharField(max_length=100, verbose_name='Client Name')),
                ('sender_email', models.EmailField(max_length=254, verbose_name='Contact Email')),
                ('transmitted_payload', models.TextField(verbose_name='Message Body')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
